OBPIH-3242 Add source name to PO lines export and import
openboxes/openboxes pull request #1934
Opened 2020-09-28 09:08 UTC by DominikaHatala

2020-09-28 11:53 UTC, awalkowiak approved these changes

2020-09-28 19:01 UTC, jmiranda requested changes

2020-09-28 19:01 UTC, jmiranda commented on grails-app/services/org/pih/warehouse/data/ProductSupplierDataService.groovy
> +        productSupplier.name = params.sourceName ?: params.supplierCode
I think we should ask kelsey about this, but I think this should probably be one of two options:

Option A
```
productSupplier.name = params.sourceName ?: product?.name
```
Option B
```
productSupplier.name = params.sourceName ?: null
```
I believe Kelsey mentioned that she would prefer Option B, but let's ask her.

2020-09-28 19:43 UTC, jmiranda commented on grails-app/services/org/pih/warehouse/data/ProductSupplierDataService.groovy
> +        productSupplier.name = params.sourceName ?: params.supplierCode
Kelsey says use product.name so let's go with Option A.

2020-09-29 07:48 UTC, DominikaHatala commented
@jmiranda I have updated this PR with requested changes

2020-09-29 16:33 UTC, awalkowiak commented
Looks like everything is fine now. I am merging this.

2020-09-29 16:33 UTC, merged