OBPIH-3589 Fix Product Source import validation
openboxes/openboxes pull request #2226
Opened 2021-02-26 18:03 UTC by pmuchowski

2021-03-01 03:56 UTC, jmiranda reviewed
Looks good, I just want to hear what's going on with the rating type field.

2021-03-01 03:56 UTC, jmiranda commented on grails-app/services/org/pih/warehouse/data/ProductSupplierDataService.groovy
> +            if (ratingType && !RatingTypeCode.values().any { it.name == ratingType.toString().toUpperCase() }) {
Could you explain this change?

2021-03-02 05:22 UTC, jmiranda requested changes

2021-03-02 05:22 UTC, jmiranda commented on grails-app/services/org/pih/warehouse/data/ProductSupplierDataService.groovy
> +            if (ratingType && !RatingTypeCode.values().any { it.name == ratingType.toString().toUpperCase() }) {
Ok, so I read the comments in the ticket and now I understand the issue. There are two ways I would prefer to have this done. First we should be initializing the value 

So either of the following two are fine. 
```
def ratingTypeCode = params?.ratingTypeCode?.toUpperCase() as RatingTypeCode
```
OR
```
def ratingTypeCode = RatingTypeCode.valueOf(params?.ratingTypeCode?.toUpperCase()))
```
The above declaration will likely cause a hard failure on invalid values so the validation below is probably not necessary (I'm ok with that). But for completeness, let's include it. I feel uncomfortable converting to a string, so I think I'd prefer the following. 
```
if (ratingTypeCode && !(ratingTypeCode in RatingTypeCode.values()))
```
Or add a validation method that can be more easily unit tested to the enum itself.
```
RatingTypeCode.inList(RatingTypeCode)
```

2021-03-03 04:44 UTC, jmiranda approved these changes

2021-03-03 14:04 UTC, awalkowiak approved these changes

2021-03-03 14:04 UTC, merged