OBPIH-3636 Allow user to change destination on PO for purchasing loca…
openboxes/openboxes pull request #2257
Opened 2021-03-09 09:34 UTC by DominikaHatala

…tions

2021-03-09 16:24 UTC, jmiranda requested changes
LGTM otherwise.

2021-03-09 16:24 UTC, jmiranda commented on grails-app/controllers/org/pih/warehouse/order/PurchaseOrderController.groovy
>          Order order = new Order()
Let's move the logic to a method on the order service so it's easier to unit test.
```
OrderService.createNewPurchaseOrder(Location currentLocation)
```

2021-03-11 08:37 UTC, DominikaHatala commented
@jmiranda I have updated this PR with required changes.

2021-03-11 21:20 UTC, jmiranda approved these changes

2021-03-12 02:40 UTC, merged