OBPIH-3042;OBPIH-3039 Create landing page for cycle count report and …
openboxes/openboxes pull request #2301
Opened 2021-03-24 11:22 UTC by DominikaHatala

…align it with inventory import

2021-03-29 11:00 UTC, awalkowiak requested changes

2021-03-29 11:03 UTC, DominikaHatala commented on grails-app/controllers/org/pih/warehouse/reporting/ReportController.groovy
> +                            "Comment"             : "",
Yes, those columns are needed for inventory import - cycle count report had to be refactored so it's aligned to inventory import.

2021-03-29 11:03 UTC, DominikaHatala commented on grails-app/views/report/showCycleCountReport.gsp
> +<div class="body">
No, I forgot about this part because there were no instruction added in the ticket. I will ask Kelsey about it.

2021-03-29 11:05 UTC, DominikaHatala commented on grails-app/controllers/org/pih/warehouse/reporting/ReportController.groovy
> +                            productCode       : StringEscapeUtils.escapeCsv(row?.product?.productCode),
You're right. I have first created landing page for html version and then changed downloaded version to be aligned with inventory item. I will change order of columns  on html version too.

2021-03-31 05:38 UTC, jmiranda approved these changes

2021-03-31 08:43 UTC, awalkowiak approved these changes

2021-03-31 08:43 UTC, merged