OBPIH-3837, OBPIH-3843 Added fields and filters on invoice list page
openboxes/openboxes pull request #2395
Opened 2021-05-11 18:59 UTC by awalkowiak

2021-05-11 21:09 UTC, jmiranda requested changes

2021-05-11 21:09 UTC, jmiranda commented on grails-app/domain/org/pih/warehouse/invoice/InvoiceList.groovy
> +    String vendor // = party.code + " " + part.name
Why not just have vendorCode and vendorName?

2021-05-11 21:09 UTC, jmiranda commented on grails-app/domain/org/pih/warehouse/invoice/InvoiceList.groovy
> +    String vendor // = party.code + " " + part.name
... and let the UI handle the concatentation.

2021-05-11 21:09 UTC, jmiranda commented on grails-app/migrations/views/invoice-list.sql
> +         invoice.id as id,
This will break the PK if there's more than one VENDOR_INVOICE_NUMBER reference number, so let's remove this column and use a composite key.

2021-05-12 09:36 UTC, awalkowiak commented
@jmiranda done

2021-05-12 17:05 UTC, jmiranda approved these changes

2021-05-12 17:05 UTC, merged