OBAM-69,165 Return quantity available to promise as quantity available
openboxes/openboxes pull request #2497
Opened 2021-06-24 14:26 UTC by awalkowiak

2021-06-24 20:12 UTC, jmiranda approved these changes
lgtm

2021-06-25 17:21 UTC, jmiranda requested changes

2021-06-25 17:21 UTC, jmiranda commented on grails-app/controllers/org/pih/warehouse/inventory/InventoryItemController.groovy
> +            def totalQuantityAvailableToPromise = productAvailabilityService.getQuantityAvailableToPromise(cmd.product, cmd.warehouse)
Let's move this inside getStockCardCommand() method if possible just so it happens any time we get the stock card command object.

2021-06-25 17:21 UTC, jmiranda commented on grails-app/views/layouts/stockCard.gsp
> +                            totalQuantity: commandInstance?.totalQuantity,
Formatting issue here.

2021-06-25 17:21 UTC, jmiranda commented on grails-app/views/layouts/stockCard.gsp
> +                            totalQuantity: commandInstance?.totalQuantity,
And with the requested change above this should probably look like this:
```
totalQuantityAvailableToPromise: commandInstance?.totalQuantityAvailableToPromise
```

2021-06-25 17:21 UTC, jmiranda commented on grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy
> +    Integer calculateQtyATP(Integer onHandQuantity, Integer quantityAllocated, Integer quantityOnHold) {
This is nit-picky, but let's keep the name consistent to avoid confusion.
```
calculateQuantityAvailableToPromise()
```

2021-06-25 17:21 UTC, jmiranda commented on grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy
> +        def qtyATP = onHandQuantity - quantityAllocated - quantityOnHold
same here
```
def quantityAvailableToPromise = quantityOnHand - quantityAllocated - quantityOnHold
```

2021-06-25 17:21 UTC, jmiranda commented
Just a few minor changes.

2021-06-26 17:06 UTC, awalkowiak commented on grails-app/views/layouts/stockCard.gsp
> +                                                        inventoryInstance:commandInstance?.inventory,
I don't get these indentations. In IDE these are aligned to the first param...

2021-06-26 17:08 UTC, awalkowiak commented
@jmiranda I pushed requested changes

2021-06-28 14:17 UTC, jmiranda approved these changes

2021-06-29 02:47 UTC, jmiranda approved these changes

2021-06-29 02:47 UTC, merged