OBPIH-3910 Don't update prepayment invoice when PO changed
openboxes/openboxes pull request #2501
Opened 2021-06-28 08:57 UTC by pmuchowski

2021-06-28 09:13 UTC, awalkowiak requested changes

2021-06-28 09:13 UTC, awalkowiak commented on grails-app/domain/org/pih/warehouse/invoice/InvoiceItem.groovy
> +        return orderAdjustment ? unitPrice : totalItemPrice
Seems like this is redundant now. InvoiceItem's quantity for adjustments should always be 1, hence you could use only the totalItemprice here (and store always the unit price here https://github.com/openboxes/openboxes/pull/2501/files#diff-f341b7100f86cf5e8f25a73606a5b1d3b49dc9238037ba24cc724889f1bc216dR244, without multiplying it with prepayment percentage)

2021-06-28 09:13 UTC, awalkowiak commented on grails-app/services/org/pih/warehouse/invoice/InvoiceService.groovy
> +                item.quantity = orderItem.quantity
I am not sure about refreshing the quantity. Was it requested?

2021-06-28 09:13 UTC, awalkowiak commented on grails-app/services/org/pih/warehouse/invoice/InvoiceService.groovy
> +                item.quantity = shipmentItem.quantity ? shipmentItem.quantity/orderItem.quantityPerUom : 0
I am not sure about refreshing the quantity. Was it requested?

2021-06-28 13:46 UTC, jmiranda requested changes

2021-06-28 13:46 UTC, jmiranda commented on grails-app/services/org/pih/warehouse/invoice/InvoiceService.groovy
> +    def refreshInvoiceValues(Invoice invoice) {
Let's call this refreshInvoice or refreshInvoiceItems instead of refreshInvoiceValues as the latter is somewhat ambiguous.

2021-06-29 02:54 UTC, jmiranda approved these changes

2021-06-29 02:55 UTC, jmiranda commented
@pmuchowski Can you fix the merge conflict?
@awalkowiak When that is done, please review and merge so that we can get this into QA.

2021-06-29 08:41 UTC, awalkowiak approved these changes

2021-06-29 08:41 UTC, merged