OBAM-234 Prevent autopick of recalled lot
openboxes/openboxes pull request #2519
Opened 2021-07-07 13:23 UTC by pmuchowski

2021-07-07 18:38 UTC, jmiranda requested changes

2021-07-07 18:38 UTC, jmiranda commented on src/groovy/org/pih/warehouse/api/StockMovementItem.groovy
> +    def getIsAutopickable() {
I think my only beef is with the camelcase so let's go with isAutoPickable to make it more readable.

2021-07-07 18:38 UTC, jmiranda commented on grails-app/domain/org/pih/warehouse/inventory/InventoryItem.groovy
> +    def getIsAutopickable() {
Also I always forget the convention when it comes to boolean properties, but I think you can just add "autoPickable" to the transients and isAutoPickable() as the method name.

2021-07-07 18:38 UTC, jmiranda commented on grails-app/domain/org/pih/warehouse/inventory/InventoryItem.groovy
> +    def getIsAutopickable() {
https://stackoverflow.com/questions/5322648/for-a-boolean-field-what-is-the-naming-convention-for-its-getter-setter

2021-07-08 09:05 UTC, awalkowiak approved these changes

2021-07-08 09:06 UTC, merged