OBPIH-4211 Formatting changes to verifyRequest editPage
openboxes/openboxes pull request #2876
Opened 2021-12-20 09:18 UTC by MagdaToczek

2021-12-20 11:41 UTC, pmuchowski requested changes

2021-12-20 15:05 UTC, MagdaToczek commented on src/js/components/stock-movement-wizard/request/EditPage.jsx
> +        getDynamicAttr: () => ({
OK, corrected.

2021-12-20 15:12 UTC, pmuchowski commented on src/js/components/stock-movement-wizard/request/EditPage.jsx
> +          numberField: true,
is this needed on Input field?

2021-12-20 15:12 UTC, pmuchowski commented on src/js/components/stock-movement-wizard/request/EditPage.jsx
> +          numberField: true,
as above

2021-12-20 15:12 UTC, pmuchowski commented on src/js/components/stock-movement-wizard/request/EditPage.jsx
> +          numberField: true,
as above

2021-12-21 07:42 UTC, MagdaToczek commented on src/js/components/stock-movement-wizard/request/EditPage.jsx
> +          numberField: true,
It is not needed.

2021-12-21 07:42 UTC, MagdaToczek commented on src/js/components/stock-movement-wizard/request/EditPage.jsx
> +          numberField: true,
It is not needed.

2021-12-21 07:42 UTC, MagdaToczek commented on src/js/components/stock-movement-wizard/request/EditPage.jsx
> +          numberField: true,
It is not needed.

2021-12-21 09:43 UTC, pmuchowski approved these changes

2021-12-21 09:43 UTC, merged