OBDX-21 T3. Create endpoint for order creation messages
openboxes/openboxes pull request #2883
Opened 2021-12-22 14:43 UTC by chetanmaharishi

OBDX-21 T3. Create endpoint for order creation messages

2021-12-22 17:42 UTC, jmiranda requested changes

2021-12-22 17:42 UTC, jmiranda commented on grails-app/controllers/org/pih/warehouse/notification/NotificationController.groovy
> +                    JSONObject destinationMapping = toJson(grailsApplication.config?.openboxes?.integration?.destinationMapping)
We should at least break this out into a separate method so we don't repeat the code in both places.
```
getLocationByLocationMapping(jsonObject.getString("id")
```

2021-12-22 17:42 UTC, jmiranda commented on grails-app/controllers/org/pih/warehouse/notification/NotificationController.groovy
> +                Location location = Location.findByLocationNumber(jsonObject.getString("id"))
Shouldn't this be locationNumber now?

2021-12-22 17:43 UTC, jmiranda commented
@chetanmaharishi if you don't get to these changes i'll work on the PR at some point during break.

2021-12-22 17:48 UTC, chetanmaharishi commented
I am working on these

2021-12-23 04:14 UTC, jmiranda approved these changes

2021-12-23 04:15 UTC, merged