OBDS-102 Address page and form
openboxes/openboxes pull request #3044
Opened 2022-03-15 15:55 UTC by kchelstowski

2022-03-16 12:00 UTC, pmuchowski requested changes

2022-03-16 14:24 UTC, jmiranda requested changes

2022-03-16 14:24 UTC, jmiranda commented on grails-app/controllers/org/pih/warehouse/api/LocationApiController.groovy
> +            existingLocation.save()
Need to handle the case when address fails validation.

2022-03-16 14:24 UTC, jmiranda commented on grails-app/controllers/org/pih/warehouse/api/LocationApiController.groovy
> +            existingLocation.save()
Also we should check whether the location validation handles both location and any associations.

2022-03-17 12:56 UTC, pmuchowski approved these changes

2022-03-17 12:57 UTC, merged