OBAM-271
openboxes/openboxes pull request #3148
Opened 2022-04-28 13:43 UTC by hdsldv

2022-04-28 21:29 UTC, awalkowiak requested changes
@hdsldv 
About your todos from ticket:
- you can simply hide specific values by doing: `hasRoleFinance ? value : ''`
- I am not sure what's the 'time period' in this case.

2022-04-28 21:29 UTC, awalkowiak commented on grails-app/controllers/org/pih/warehouse/reporting/ConsumptionController.groovy
> +                if(!user.roles.contains(RoleType.ROLE_FINANCE)) {
Use `userService.hasRoleFinance(session?.user)`

2022-04-28 21:29 UTC, awalkowiak commented on grails-app/controllers/org/pih/warehouse/reporting/ConsumptionController.groovy
> +                    } else if (transaction.order.orderType.code != "PUTAWAY_ORDER" && transaction.order.orderType.code != OrderTypeCode.TRANSFER_ORDER.name()) {
Use `Constants.PUTAWAY_ORDER` for "PUTAWAY_ORDER"

2022-04-29 08:21 UTC, hdsldv commented on grails-app/controllers/org/pih/warehouse/reporting/ConsumptionController.groovy
> +                if(!user.roles.contains(RoleType.ROLE_FINANCE)) {
done

2022-05-02 15:52 UTC, hdsldv commented on grails-app/controllers/org/pih/warehouse/reporting/ConsumptionController.groovy
> +                    } else if (transaction.order.orderType.code != Constants.PUTAWAY_ORDER && transaction.order.orderType.code != OrderTypeCode.TRANSFER_ORDER.name()) {
I think it will be better to have it explicitly set

2022-05-02 15:52 UTC, hdsldv commented on grails-app/controllers/org/pih/warehouse/reporting/ConsumptionController.groovy
> +                if(!userService.hasRoleFinance(session?.user)) {
right, done

2022-05-04 07:35 UTC, awalkowiak approved these changes

2022-05-04 07:35 UTC, merged