OBPIH-4403 Unable to receive inbound returns
openboxes/openboxes pull request #3189
Opened 2022-05-11 08:46 UTC by kchelstowski

2022-05-11 09:37 UTC, awalkowiak requested changes

2022-05-11 09:37 UTC, awalkowiak commented on grails-app/services/org/pih/warehouse/receiving/ReceiptService.groovy
> +                    inventoryService.findOrCreateInventoryItem(
This should be done in the StockTransferApiController and StockTransferService side. Debug why it is not working there.

2022-05-11 20:13 UTC, kchelstowski commented
@awalkowiak after a long research it unexpectedly turned out that the changes I provided for OBPIH-4406 also resolve this task. The problem was that in StockTransferApiController the inventoryItem was created only if both lot and expirationDate weren't null. And if the inventoryItem was null, in OBPIH-4406 the product name and code weren't visible, because the data is taken from inventoryItem. 
If those changes seem to be OK for you, I think you can also merge OBPIH-4406 immedietaly as they provide the same change.

2022-05-13 11:40 UTC, awalkowiak approved these changes

2022-05-13 11:41 UTC, merged