OBPIH-4943 Fix logo display on React pages and fix active menu sectio…
openboxes/openboxes pull request #3569
Opened 2022-10-21 12:24 UTC by kchelstowski

…n while on stock list page

2022-10-21 12:59 UTC, drodzewicz requested changes
I think that `Logo.jsx` component needs some modifications.
Currently it is checking if logo `logoUrl` is not **null** and if it is not it renders the image with given logoURL and if it is **null** it renders default openboxes logo.

I think that a better approach would be to handle onError fallback on image 
```
        <img
          src={logoUrl}
          onError={e => e.target.src = OpenboxesLogo}
          alt="Openboxes"
          width="40"
          height="40"
          role="presentation"
          onClick={() => history.push('/openboxes')}
        />
```
The reason for that is that even if `logoURL` might not be **null**, we can always expect the link to be wrong/broken, so in case of handling onError it would set it to openboxes default logo if there is something wrong with the image

2022-10-21 13:18 UTC, kchelstowski commented
@drodzewicz it's nice to know - I hadn't known about `onError` before to be honest. Will try to refactor this. I assume, that instead of giving `alt` when it doesn't find the logo on theoretically good url (not null), it wouldn't give the `alt`, but provide us a default logo? 
And saying that, the `alt` would only display if it doesn't find the image on `logoUrl` and the default logo would not be found?

2022-10-21 13:46 UTC, drodzewicz commented
> @drodzewicz it's nice to know - I hadn't known about `onError` before to be honest. Will try to refactor this. I assume, that instead of giving `alt` when it doesn't find the logo on theoretically good url (not null), it wouldn't give the `alt`, but provide us a default logo? And saying that, the `alt` would only display if it doesn't find the image on `logoUrl` and the default logo would not be found?

yes, if `logoUrl` is wrong it would then display defaultLogo then if defaultLogo is wrong then alt text will appear

2022-10-21 18:27 UTC, drodzewicz approved these changes

2022-10-24 08:21 UTC, awalkowiak approved these changes

2022-10-24 16:09 UTC, merged