OBPIH-5006 obtrusive menu in mobile browser
openboxes/openboxes pull request #3606
Opened 2022-11-04 16:58 UTC by drodzewicz

2022-11-04 17:06 UTC, kchelstowski approved these changes

2022-11-04 17:42 UTC, awalkowiak requested changes
Code-wise I think it looks ok, but locally for me, the initial megamenu from gsp template takes around 20s to build. Plus there is a tiny difference in both headers height.

2022-11-07 16:50 UTC, kchelstowski approved these changes

2022-11-07 17:22 UTC, awalkowiak approved these changes

2022-11-08 09:57 UTC, merged