OBPIH 5231 Add front-end unit tests for Wizard and Menu components
openboxes/openboxes pull request #3701
Opened 2022-12-12 12:08 UTC by alannadolny

2022-12-12 14:40 UTC, jmiranda reviewed
Great idea @awalkowiak 

@alannadolny Can you explain why you deleted the jar file?

2022-12-12 14:48 UTC, awalkowiak commented
@jmiranda my blind guess: this is some weird issue after IDE setup. I locally created a fresh branch from develop and cherry-picked these commits and this lib removal change is no longer there. Plus, as you can see currently this `lib/something.jar` does not exists in the develop branch. We will sort this out.

2022-12-12 15:02 UTC, drodzewicz requested changes

2022-12-13 09:45 UTC, drodzewicz approved these changes

2022-12-13 10:19 UTC, merged