OBPIH-5195 fix displaying dropdowns
openboxes/openboxes pull request #3730
Opened 2022-12-22 08:23 UTC by alannadolny

2022-12-22 08:44 UTC, drodzewicz requested changes

2022-12-22 08:44 UTC, drodzewicz commented on src/js/components/Layout/menu/MenuSubsection.jsx
> +  const [droppedDown, setDroppedDown] = useState(false);
I would call this state `[isOpen, setIsOpen] ` instead of `[droppedDown, setDroppedDown]`

2022-12-22 08:44 UTC, drodzewicz commented on src/js/components/Layout/menu/MenuSubsection.jsx
> +  const shouldAlignLeft = (ref) => {
I think that you don't need to have a `ref` as an argument here, you can just call the `dropdownRef` directly in the function body

2022-12-22 08:44 UTC, drodzewicz commented on src/js/components/Layout/menu/MenuSubsection.jsx
> +  };
this method can be simplified to 
```
const shouldAlignLeft = () => {
    if (dropdownRef.current && isOpen) {
      const elementCoordinates = ref.current.getBoundingClientRect();
      return window.innerWidth > elementCoordinates.right + elementCoordinates.width;
    }
    return false;
}
```

other than that everything looks good to me, good job.

2022-12-22 08:59 UTC, kchelstowski requested changes
What about moving it to a custom hook, as it might be useful in the future?

2022-12-22 09:12 UTC, kchelstowski requested changes

2022-12-22 09:12 UTC, kchelstowski commented on src/js/hooks/useCheckRightSpace.jsx
> +export default useCheckRightSpace;
this is not a hook - what I meant is to move `ref` and `states` logic to a hook, so you could return them in the hook like this:
```
return { dropdownRef, isOpen, setIsOpen }
```
and you could use it in the component like this:
```
const { dropdownRef, isOpen, setIsOpen } = useCheckRightSpace();
```
remember to change the names in the hook to generic ones, but in the component you could do:
```
const { dropdownRef: <ref_name_from_hook> } 
```

2022-12-22 09:15 UTC, kchelstowski commented on src/js/hooks/useCheckRightSpace.jsx
> +export default useCheckRightSpace;
remember also about moving your function `shouldAlignLeft` to the hook

2022-12-22 09:19 UTC, kchelstowski approved these changes

2022-12-23 21:56 UTC, awalkowiak approved these changes

2022-12-23 21:56 UTC, merged