OBPIH-5267 Create API architecture for React side for rest list pages
openboxes/openboxes pull request #3746
Opened 2023-01-02 11:58 UTC by alannadolny

2023-01-02 20:58 UTC, kchelstowski requested changes

2023-01-02 20:58 UTC, kchelstowski commented on src/js/api/services/StockListApi.js
> +  STOCK_LIST_PUBLISH, STOCK_LIST_UNPUBLISH,
we should keep stocklist as `STOCKLIST` as it is a proper name.
so:
```
STOCKLIST_API
```
etc.

2023-01-03 20:56 UTC, jmiranda commented
@drodzewicz can you review this PR?

2023-01-03 20:56 UTC, jmiranda commented
@drodzewicz nevermind, @kchelstowski says this one is ready to merge.

2023-01-03 20:58 UTC, merged

2023-01-17 19:24 UTC, awalkowiak commented
This is good, but I think this will be a pain in the ass while rebasing grails 3 on top of this (but I'll manage it, hopefuly). Definitely this refactor should be done before starting the grails 3.