OBPIH-5217 Add missing translations for stock card
openboxes/openboxes pull request #3755
Opened 2023-01-04 13:55 UTC by drodzewicz

2023-01-05 09:39 UTC, kchelstowski requested changes

2023-01-05 09:39 UTC, kchelstowski commented on grails-app/views/inventoryItem/_showPendingOutboundStock.gsp
> +    <h2><warehouse:message code="stockCard.pendingOutbound.label"/></h2>
I can't see a default message here

2023-01-05 15:57 UTC, kchelstowski approved these changes

2023-01-05 18:00 UTC, jmiranda requested changes

2023-01-05 18:00 UTC, jmiranda commented on grails-app/views/product/_summary.gsp
> +							${warehouse.message(code: 'default.edit.label', args:[g.message(code: 'product.label', 'product')])}
Capitalize "Product" here and "Stock" above (in "Record Stock").

2023-01-10 09:16 UTC, kchelstowski approved these changes

2023-01-10 15:18 UTC, jmiranda approved these changes

2023-01-10 15:18 UTC, merged