OBPIH-5414 See product name translation based on "product locale" (Scope: returns)
openboxes/openboxes pull request #3842
Opened 2023-02-15 10:07 UTC by alannadolny

2023-02-15 11:23 UTC, drodzewicz requested changes
you have pushed `lib > classpath.index` file which is probably not supposed to be in this PR.
Please remove it

other than that LGTM

2023-02-15 11:23 UTC, drodzewicz commented on src/js/components/returns/inbound/SendInboundReturn.jsx
> +          formatValue: value => (
good job on this refactor

2023-02-15 11:53 UTC, kchelstowski requested changes

2023-02-15 11:53 UTC, kchelstowski commented on grails-app/controllers/org/pih/warehouse/api/StockTransferApiController.groovy
> -
is it necessary?

2023-02-15 12:31 UTC, drodzewicz approved these changes

2023-02-16 06:13 UTC, jmiranda reviewed
LGTM

2023-02-16 11:34 UTC, awalkowiak approved these changes

2023-02-16 15:16 UTC, merged