WIP: OBPIH-5481 Refactor product API to handle localized product names
openboxes/openboxes pull request #3880
Opened 2023-03-03 14:47 UTC by jmiranda

2023-03-06 09:56 UTC, kchelstowski requested changes
As soon as we "collect" all request changes and agree on the final version, I could jump to that and fix it and test it.
I think a good idea here would be to write some unit tests for that? Any thoughts guys?

2023-03-06 09:56 UTC, kchelstowski commented on grails-app/domain/org/pih/warehouse/product/Product.groovy
> +        def locales = supportedLocales.collect { return new Locale(it) }
I think we could at least add those two lines to `LocalizationUtil`, as I can see the same logic is applied in the method below.

```groovy
static List<Locale> getSupportedLocales() {
   def supportedLocales = ConfigurationHolder.config.openboxes.locale.supportedLocales
   return supportedLocales.collect { return new Locale(it) }
}
```

and do here:
```suggestion
        List<Locale> supportedLocales = LocalizationUtil.supportedLocales
```

2023-03-06 09:56 UTC, kchelstowski commented on grails-app/domain/org/pih/warehouse/product/Product.groovy
> +        def data = ["": getDisplayName(LocalizationUtil.currentLocale)]
As you wrote above, I think it should be immediately:
```suggestion
        def data = ["default": getDisplayName(LocalizationUtil.currentLocale)]
```

2023-03-07 10:02 UTC, awalkowiak commented on grails-app/domain/org/pih/warehouse/product/Product.groovy
> +        // FIXME If you cannot retrieve this easily just change the empty string ("") to "default"
```suggestion
```

2023-03-07 11:01 UTC, awalkowiak commented
Remaining ToDos:
1. Remove unused code from the first version of the code (alias and aliases getters)
2. Create a method similar to `translatedNameWithLocaleCode` (but based on `displayName`) for future replacement (and create a ticket for it or replace if it will be easy and fast to test)
3. Add LocalizationUtil.supportedLocales (and create ticket to replace other existing usage od `supportedLocales`)
4. If there will be a time add also some unit tests for the `displayName`
5. Create tickets for change from `translatedName` to `displayName?.default` (or `translatedNameWithLocaleCode` to the new version of it). Plus add old version PRs links in the description if possible:

    - Raports  where `translatedNameWithLocaleCode` is used **(3 SP)**,
    - Gsp templates (views + reports) where `.translatedName` is used (if possible, replace with TagLib) **(2 SP / blocked by the TagLib ticket)**,
    - Uploaded pdfs file templates **(2 SP)**,
    - refactor `hasTranslatedName` for the new version (+ global search) **(2 SP)**,
    - refactor TranslatedProductNameTagLib for the `displayName` (and move to the formatTagLib or productTagLib - see what was requested) **(3 SP)**, 
    - replace `.translatedName` (or `translatedProductName` or `productTranslatedName`) with `displayName` on react pages,

        - stock movement (outbound + inbound + modals) **(3 SP)**,
        - return (outbound + inbound) + combined shipment **(2 SP)**,
        - stock request + receiving + invoice **(2 SP)**,
        - product select + products + select **(3 SP)**.

2023-03-08 10:36 UTC, drodzewicz requested changes

2023-03-08 10:36 UTC, drodzewicz commented on grails-app/domain/org/pih/warehouse/product/Product.groovy
> +            }
```suggestion
            if (displayName) {
                data.put(locale.toLanguageTag(), displayName)
            }
```
other than this small suggestion LGTM

2023-03-08 10:41 UTC, kchelstowski commented on grails-app/domain/org/pih/warehouse/product/Product.groovy
> +            }
that's a bummer, thanks

2023-03-08 10:48 UTC, drodzewicz approved these changes

2023-03-08 17:16 UTC, merged