OBPIH-5499 Refactor format:product taglib to display localized product synonym DISPLAY_NAME
openboxes/openboxes pull request #3903
Opened 2023-03-09 15:55 UTC by drodzewicz

2023-03-09 18:04 UTC, kchelstowski requested changes

2023-03-10 09:23 UTC, awalkowiak requested changes

2023-03-10 09:23 UTC, awalkowiak commented on grails-app/taglib/org/pih/warehouse/FormatTagLib.groovy
> +        if (attrs.product) {
Let's move it to the `FormatTagLib` as a `<format:displayName ...>`

2023-03-10 13:53 UTC, awalkowiak approved these changes

2023-03-10 13:56 UTC, merged