OBPIH-5433 Add Validation for Stock Movement deletion (fix after QA)
openboxes/openboxes pull request #3960
Opened 2023-03-31 10:39 UTC by alannadolny

2023-03-31 10:55 UTC, drodzewicz approved these changes

2023-04-03 04:43 UTC, kchelstowski requested changes

2023-04-03 04:43 UTC, kchelstowski commented on grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy
> +                def message = "${warehouse.message(code: 'stockMovement.delete.error.message')}"
We want to get rid of `warehouse.message` at some points, so let's use `g.message` if possible. Consider adding a default message also.
```suggestion
                def message = "${g.message(code: 'stockMovement.delete.error.message')}"
```

2023-04-03 04:43 UTC, kchelstowski commented on grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy
> +                        def message = "${warehouse.message(code: 'stockMovement.delete.error.message')}"
same as above

2023-04-03 04:43 UTC, kchelstowski commented on grails-app/controllers/org/pih/warehouse/inventory/StockMovementController.groovy
> +                    flash.message = "${warehouse.message(code: 'stockMovement.delete.error.message')}"
same as above

2023-04-03 08:22 UTC, kchelstowski requested changes

2023-04-03 08:22 UTC, kchelstowski commented on grails-app/controllers/org/pih/warehouse/inventory/StockMovementController.groovy
> +                    flash.message = "${g.message(code: 'stockMovement.delete.error.message', body: 'The Stock Movement could not be deleted')}"
Why are you using `body`?
```suggestion
                    flash.message = "${g.message(code: 'stockMovement.delete.error.message', default: 'The Stock Movement could not be deleted')}"
```

2023-04-03 09:09 UTC, kchelstowski approved these changes

2023-04-03 09:23 UTC, awalkowiak approved these changes

2023-04-03 09:55 UTC, merged