OBGM-486 Unable to upload documents on view shipment page
openboxes/openboxes pull request #4108
Opened 2023-06-15 09:50 UTC by alannadolny

2023-06-15 10:27 UTC, awalkowiak requested changes
I did this regex search in grails-app folder: `log\.(info|debug|error)[ |(][^\"|^\']` and there are also two instances of `log.debug params` plus a couple of instances of logging maps. Please change the "debug params" and check if Map also triggers this issue.

2023-06-15 12:08 UTC, alannadolny commented on grails-app/controllers/org/pih/warehouse/user/DashboardController.groovy
>      }
I am not sure if this method is used somewhere

2023-06-15 13:31 UTC, kchelstowski approved these changes
it LGTM, but I'm actually wondering if you have a clear answer why it is not working and has worked for Grails 1? What changed?

2023-06-16 08:48 UTC, awalkowiak approved these changes

2023-06-16 08:51 UTC, merged