OBGM-516 Unable to run inventory by location report
openboxes/openboxes pull request #4112
Opened 2023-06-16 14:34 UTC by alannadolny

2023-06-16 14:36 UTC, alannadolny commented on src/main/groovy/org/pih/warehouse/report/MultiLocationInventoryReportCommand.groovy
> +        return actionButton?.equalsIgnoreCase("download") ?: false
This part was throwing that `isActionRun` and `isActionDownload` cannot be null, so as a solution, I am returning false when `actionButton` is null.

2023-06-19 07:02 UTC, kchelstowski commented on src/main/groovy/org/pih/warehouse/report/MultiLocationInventoryReportCommand.groovy
> +        return actionButton?.equalsIgnoreCase("run") ?: false
@alannadolny by default all Grails properties are `nullable: false`. To make it work "in a clean way", you need to add the transients to the constraints and mark them as `nullable: true`.
So to add:
```groovy
static constraints = {
...
isActionRun(nullable: true)
isActionDownload(nullable: true)
}

2023-06-19 08:06 UTC, kchelstowski approved these changes

2023-06-19 11:51 UTC, awalkowiak requested changes

2023-06-19 13:28 UTC, awalkowiak approved these changes

2023-06-19 13:28 UTC, merged