OBGM-552 Unable to add items to PO through import
openboxes/openboxes pull request #4131
Opened 2023-06-30 11:16 UTC by alannadolny

2023-06-30 11:24 UTC, kchelstowski approved these changes

2023-07-01 03:08 UTC, jmiranda approved these changes
LTGM, I guess. 

However, I don't really understand how the fix solves the problem because it's not obvious what is happening. 

@alannadolny could you please explain the issue in the ticket. What is different about YML that causes the issue. And also make sure this works if we were to override the configuration in openboxes-config.groovy.

2023-07-03 15:07 UTC, awalkowiak requested changes

2023-07-04 10:20 UTC, awalkowiak approved these changes

2023-07-04 11:10 UTC, merged