OBGM-564 items disappearing from pack and send page after editing revised qty
openboxes/openboxes pull request #4143
Opened 2023-07-06 15:14 UTC by drodzewicz

2023-07-06 15:16 UTC, drodzewicz commented
While investigating this issue there were many annoying eslint errors in the browser console so I decided to fix some of them.
Most of them were related to the defined proptypes that didn;t match the passed prop data

2023-07-06 15:35 UTC, kchelstowski approved these changes
as for those ESLint issues, we need to adjust settings to what was in Grails 1, because I agree it's annoying

2023-07-06 15:52 UTC, awalkowiak commented on grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
> +        Requisition requisition = stockMovement.requisition.refresh()
Please, check if the recall and revert recall refresh the product availability with this `refresh()` here?

2023-07-06 21:17 UTC, jmiranda requested changes

2023-07-06 21:17 UTC, jmiranda commented on grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
> +        Requisition requisition = stockMovement.requisition.refresh()
I don't think it's missing, I think it was explicitly removed. Or maybe we used a Requisition.get() before. I think that would be fine.

2023-07-07 10:15 UTC, drodzewicz commented on grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
> +        Requisition requisition = stockMovement.requisition.refresh()
Unfortunately reverting it back to `Requisition.get(stockMovement.id)` doesn't fix the issue with reviseItems.
I tested recall and product availability refresh with the `refresh()` and it seems to be working fine, everything seems to be updated immediately.
We could wait until tech huddle to discuss this case in more detail, but at this moment I don't have any other solution other than the one currently in the PR.

2023-07-07 14:53 UTC, awalkowiak commented on grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
> +        Requisition requisition = stockMovement.requisition.refresh()
@drodzewicz I'm fine with restoring the `refresh()`, but could you add also a comment in the code on why it is needed there?

2023-07-10 08:12 UTC, awalkowiak approved these changes

2023-07-10 08:13 UTC, merged