OBGM-619 Include out of stock checkbox not working on inventory browser
openboxes/openboxes pull request #4203
Opened 2023-08-02 12:17 UTC by alannadolny

The `showOutOfStockProducts` was not bound correctly, it is explained here: https://stackoverflow.com/questions/60990362/grails-command-object-not-binding-to-def-type

Part of the documentation linked in question above:
> Properties which are not bindable by default are those related to transient fields, dynamically typed properties and static properties.

2023-08-02 14:20 UTC, kchelstowski approved these changes

2023-08-02 14:21 UTC, kchelstowski commented
I am wondering if you shouldn't also change the booleans above. Won't they also cause problems in the future?

2023-08-02 14:49 UTC, alannadolny commented
As I remember, we discussed on the tech huddle that we shouldn't do more work than it's described in the ticket to track the changes better. Moreover, it needs some checks about how it is used - is it set in the searching function, or should it be just bound from the params.

2023-08-02 15:33 UTC, awalkowiak requested changes

2023-08-02 15:33 UTC, awalkowiak commented on src/main/groovy/org/pih/warehouse/inventory/InventoryCommand.groovy
> +    Boolean showOutOfStockProducts = Boolean.FALSE
I think this should be also done for the booleans above since it will be causing the same issue.

2023-08-03 15:55 UTC, awalkowiak approved these changes

2023-08-03 15:55 UTC, merged