OBGM-633 Data chooser issues on record stock page
openboxes/openboxes pull request #4230
Opened 2023-08-17 14:44 UTC by alannadolny

2023-08-20 15:52 UTC, jmiranda reviewed
I don't like this syntax (`[Calendar.YEAR]`) but it seems like it was added a long time ago so I won't block this from being.
```
${ConfigHelper.getMinimumExpirationDate()[Calendar.YEAR]}
```
Either of the following seem more intuitive and correct.
```
${ConfigHelper.getMinimumExpirationDate().year}
```
or
```
${ConfigHelper.getMinimumExpirationDate().get(Calendar.YEAR)}
```

2023-08-21 06:41 UTC, kchelstowski approved these changes

2023-08-21 07:33 UTC, drodzewicz requested changes
having something like 
`${ConfigHelper.minimumExpirationDate.year}`
would be the best and nicer solution but I feel like it is going to be harder to implements.

Correct me if I am wrong, but I believe when you have a getter class method specified like `def getSomething` you can access it's value by calling the property without get and a method call like `obj.something`.
 
So I think for now just use

```groovy
ConfigHelper.minimumExpirationDate[Calendar.YEAR]
```

2023-08-21 07:41 UTC, drodzewicz approved these changes

2023-08-21 07:41 UTC, alannadolny commented
@jmiranda `.year` is marked as deprecated and the `.get` method throws an exception. So, I am finally changing this to the version that Dariusz proposed.

2023-08-21 13:32 UTC, awalkowiak approved these changes

2023-08-21 15:33 UTC, merged