OBGM-682 Remove locations withour organization from destination dropdown on PO create page
openboxes/openboxes pull request #4248
Opened 2023-08-25 13:15 UTC by drodzewicz

2023-08-25 13:43 UTC, kchelstowski commented on grails-app/views/purchaseOrder/_enterOrderDetails.gsp
> +                                                          hasOrganization="${true}"
I think `withOrganization` would sound better? :thinking:  but since I'm not master of naming, treat it as a loose suggestion

2023-08-25 13:43 UTC, kchelstowski commented on grails-app/taglib/org/pih/warehouse/SelectTagLib.groovy
> +                attrs.from = attrs.from.findAll { !!it.organization }
I think the double negation is not needed here, `it.organization` should be enough.

2023-08-25 13:46 UTC, kchelstowski commented
And a clarifying question - is it something that was also not working in Grails 1 and that we decided to fix now? Because I kinda don't see any reason why it would work in Grails 1?

2023-08-25 13:52 UTC, drodzewicz commented
> And a clarifying question - is it something that was also not working in Grails 1 and that we decided to fix now? Because I kinda don't see any reason why it would work in Grails 1?

sorry for not clarifying this in the PR, I left a [comment under the ticket ](https://pihemr.atlassian.net/browse/OBGM-682?focusedCommentId=145217)

Basically, there was a change I did not too long ago, adding an additional condition to **origin** and **destination** constraint validators which in a way caused this issue. Additionally, I would need to add some new condition that would throw this error for Orders from PO but I feel this validator will become too big and unreadable, so after talking about it with Katarzyna we decided to just hide these locations from the dropdown

2023-08-28 13:40 UTC, awalkowiak requested changes

2023-08-28 13:40 UTC, awalkowiak commented on grails-app/taglib/org/pih/warehouse/SelectTagLib.groovy
> +                attrs.from = attrs.from.findAll { !!it.organization }
What's the point of filtering it here if you can already filter it at the "fetching" level

2023-08-29 16:12 UTC, awalkowiak approved these changes

2023-08-29 16:12 UTC, merged