OBPIH-4930 Show catalog colors on outbound shipment pages
openboxes/openboxes pull request #4434
Opened 2023-12-22 19:35 UTC by alannadolny

2024-01-03 20:17 UTC, kchelstowski approved these changes

2024-01-04 19:53 UTC, jmiranda requested changes
One overarching concern would be with performance. I can't remember if "color" property is an N+1 query or a formula. But if it's backed by an N+1 query then we could potentially have a 4*N+1 query problem here. Actually, more since we have at least one forEach loops in there. 

So we should consider moving that to a separate tag (format:displayProductWithColor) that invokes the format:displayProduct tag.

And then we can probably use caching on top of that. 

https://grails.github.io/grails-cache/4.0.3/guide/index.html#cacheTags

2024-01-04 19:53 UTC, jmiranda commented on grails-app/init/org/pih/warehouse/BootStrap.groovy
> +                "product.color"         : picklistItem?.inventoryItem?.product?.color,
I'm cool with this one for now. But eventually, I will replace all of these fake nested objects with a proper JSON object graph. I'm going to be working on these issues over the next few months so let's keep that in mind and let me know if there's anything in particular we'll need to deal with on the client side when that happens.

2024-01-04 19:53 UTC, jmiranda commented on grails-app/views/requisition/_showRequisitionItem.gsp
> +                <span style="color: ${requisitionItem?.product?.color ?: "black"}">
Lastly, is there any advantage to moving the display logic into the format:displayName tag? In particular, we could standardize on using that tag any time we need to display the product name. However, we'd have to potentially make some changes to the tag to support HTML vs non-HTML callers. In other words, we don't want to add a span tag to JSON object used in a non-HTML context.

2024-01-05 09:52 UTC, alannadolny commented on grails-app/views/requisition/_showRequisitionItem.gsp
> +                <span style="color: ${requisitionItem?.product?.color ?: "black"}">
I don't think so, that moving this display logic to this tag is a good idea. In the ticket, it was described to add colors on specific pages - adding colors to this tag will affect more than those listed pages.

2024-01-05 10:50 UTC, alannadolny commented
@jmiranda I can see that the color is a formula. I created a custom tag for adding color to the product name, and I also used caching as you suggested.

2024-01-09 14:06 UTC, awalkowiak approved these changes
Looks like all change requests were resolved, and it lgtm.

2024-01-09 14:07 UTC, merged