OBPIH-6101 Create a reusable Switch component
openboxes/openboxes pull request #4492
Opened 2024-02-06 09:24 UTC by alannadolny

2024-02-06 09:31 UTC, awalkowiak requested changes

2024-02-06 09:31 UTC, awalkowiak commented on src/js/components/form-elements/v2/Switch.jsx
> +    <div id="switch-container">
Why you are using `id` here? What if there are going to be multiple switch fields on the form for some usecase?

2024-02-06 09:31 UTC, awalkowiak commented on src/js/components/form-elements/v2/Switch.jsx
> +          id="toggle"
I fell like this could use some sort of additional part of id passed in props :thinking:

2024-02-06 09:37 UTC, kchelstowski commented on src/js/components/form-elements/v2/Switch.jsx
> +const Switch = ({ defaultValue, titles, onChange }) => {
this should be ready to receive the `...field` prop from the `react-hook-form`. I can't exactly say now what all the props will be, so for now let's at least add it as `...rest` (let's name it as `...fieldProps`).

2024-02-06 11:57 UTC, drodzewicz approved these changes

2024-02-07 07:34 UTC, kchelstowski approved these changes

2024-02-07 13:49 UTC, awalkowiak approved these changes

2024-02-07 14:19 UTC, merged