OBPIH-6365 Add import validation on quantity available when item is picked
openboxes/openboxes pull request #4664
Opened 2024-06-12 10:57 UTC by drodzewicz

2024-06-13 12:44 UTC, drodzewicz commented on grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
> +                Boolean isPickedItemPickable = availableItem?.status == AvailableItemStatus.PICKED && !availableItem.isPickable(data?.quantityAsNumber)
you are right, looking at the code something doesn't logically add up.
So the case that this part is trying to solve is to return an error for **picked quantity** if:
- item is on hold
- item is recalled
- item is unavailable (qty available < 0 )
- quantity available is less than what we are trying to pick


```groovy
Boolean isPickable() {
    return (inventoryItem ? inventoryItem.pickable : true) && (binLocation ? binLocation.pickable : true)
}
```
I did not look into the isPickable function too deep inside and based my logic on the statuses but it looks like `isPickable` actually covers a lot of these cases
The **isPickable** for inventory item
```groovy
Boolean isPickable() {
    return !recalled
}
```
and **isPickable** for on Location
```groovy
    Boolean isPickable() {
        return !onHold
    }
```
so one more case that I need to add is checking if the _quantity that we are trying to pick_ is <= _quantity available_ which should resolve to this logic in the end

```groovy
if (availableItem && availableItem.isPickable() && data?.quantityAsNumber <= availableItem.quantityAvailable) {
}
```

also I can add a method on `AvailabeItem` something like `availableItem.isRequestedAmoundAvailable(data?.quantityAsNumber )`

2024-06-14 09:30 UTC, awalkowiak requested changes

2024-06-14 09:30 UTC, awalkowiak commented on src/main/groovy/org/pih/warehouse/api/StockMovementItem.groovy
> -    }
@jmiranda uses it in his PR

2024-06-14 09:30 UTC, awalkowiak commented on src/main/groovy/org/pih/warehouse/api/StockMovementItem.groovy
> +    Boolean isPickableQuantity(Integer quantity) {
Nitpicky, but I would call it `isQuantityPickable`

2024-06-14 10:04 UTC, awalkowiak approved these changes

2024-06-14 14:57 UTC, merged